template: 
  dag_config: &shared_dag_configs
    # Configs under dag_config should have the key name as the keywords arguments of the DAG method
    default_args:
      email:
        - antony.pallupetta@experionglobal.com
      email_on_failure  : True
      email_on_retry    : True
      retries           : 2
    catchup           : False
    start_date        : 2021-12-25 00:00:00
    schedule_interval :
  common_paths: &common_project_paths
    common_path1  : some/path/to/common-location


daily_load_workflow:
  dag_config:
    <<: *shared_dag_configs
    # To override specific config, specify it separately
    schedule_interval  : 
  paths_config:
    << : *common_project_paths
    path1 : some/path/to/specific-location
