template:
  dag_config:
    schedule: 
    catch_up: False
    start_date: 2021-12-25 00:00:00
    multiple_outputs: True
  
  common_paths: &common_paths
    common_path1: some/path/to/common-location

daily_load_workflow:
  dag_config:
    schedule: 
    catch_up: False
    start_date: 2021-12-25 00:00:00
    multiple_outputs: True
  
  paths_config:
    << : *common_paths
    path1: some/path/to/specific-location
